services:
  pc-health-bot:
    build: .
    container_name: pc-health-bot
    restart: unless-stopped
    env_file:
      - .env
    # Necessary for psutil to measure the CPU/RAM and real process of physical machine/host
    pid: host
    # Necessary for network.oy measure network interfaces of machine (Including Tailscale)
    network_mode: host
    volumes:
      # Optional mounting in reading mode for psutil reads kernel host status
      - /proc:/host/proc:ro